
export const SIMULATION_REFERENCE_TIME = new Date('2026-09-04T12:00:00.000Z');
export const DEFAULT_SIMULATION_SEED = 'RECOVEROS_BUILDATHON_2026';

export const POLICY_CONFIG = {
  MAX_PAYMENT_RETRIES: 2,
  MAX_CUSTOMER_CONTACTS: 2,
  MAX_RECOVERY_WINDOW_HOURS: 48,
  HIGH_VALUE_THRESHOLD: 50000,
  MIN_COOLDOWN_MINUTES: 30,
  CONFIDENCE_THRESHOLD: 0.65
};

export const HARD_PROHIBITED_CODES = [
  'FRAUD_SUSPECTED',
  'CARD_STOLEN',
  'CARD_LOST',
  'ACCOUNT_CLOSED',
  'DO_NOT_HONOR_PERMANENT'
];

export const RAW_FAILURE_CODES = [
  'BANK_TIMEOUT',
  'INSUFFICIENT_FUNDS',
  'AUTHENTICATION_FAILED',
  'CART_ABANDONED',
  'INVOICE_OVERDUE_30D',
  'INVOICE_OVERDUE_60D',
  'INVOICE_OVERDUE_90D',
  'FRAUD_SUSPECTED',
  'CARD_STOLEN',
  'CARD_LOST',
  'ACCOUNT_CLOSED',
  'DO_NOT_HONOR_PERMANENT'
];

export const DIAGNOSIS_CATEGORIES = [
  'TEMPORARY_PAYMENT_FAILURE',
  'INSUFFICIENT_FUNDS',
  'AUTHENTICATION_FAILURE',
  'CHECKOUT_ABANDONMENT',
  'RECEIVABLE_OVERDUE',
  'FRAUD_RISK',
  'ACCOUNT_CLOSED',
  'HARD_DECLINE',
  'UNKNOWN'
];

export const FAILURE_CODE_TO_DIAGNOSIS_CATEGORY = {
  BANK_TIMEOUT: 'TEMPORARY_PAYMENT_FAILURE',
  INSUFFICIENT_FUNDS: 'INSUFFICIENT_FUNDS',
  AUTHENTICATION_FAILED: 'AUTHENTICATION_FAILURE',
  CART_ABANDONED: 'CHECKOUT_ABANDONMENT',
  INVOICE_OVERDUE_30D: 'RECEIVABLE_OVERDUE',
  INVOICE_OVERDUE_60D: 'RECEIVABLE_OVERDUE',
  INVOICE_OVERDUE_90D: 'RECEIVABLE_OVERDUE',
  FRAUD_SUSPECTED: 'FRAUD_RISK',
  CARD_STOLEN: 'HARD_DECLINE',
  CARD_LOST: 'HARD_DECLINE',
  ACCOUNT_CLOSED: 'ACCOUNT_CLOSED',
  DO_NOT_HONOR_PERMANENT: 'HARD_DECLINE'
};

export const RECOVERY_ACTIONS = {
  RETRY_PAYMENT: 'RETRY_PAYMENT',
  SEND_PAYMENT_REMINDER: 'SEND_PAYMENT_REMINDER',
  SEND_CHECKOUT_REMINDER: 'SEND_CHECKOUT_REMINDER',
  SEND_INVOICE_REMINDER: 'SEND_INVOICE_REMINDER',
  SUGGEST_ALTERNATE_PAYMENT: 'SUGGEST_ALTERNATE_PAYMENT',
  ESCALATE_TO_HUMAN: 'ESCALATE_TO_HUMAN',
  STOP_RECOVERY: 'STOP_RECOVERY'
};

export const CASE_STATES = {
  AT_RISK: 'AT_RISK',
  SCORING: 'SCORING',
  ANALYZING: 'ANALYZING',
  ACTION_PLANNED: 'ACTION_PLANNED',
  POLICY_CHECK: 'POLICY_CHECK',
  EXECUTING: 'EXECUTING',
  OBSERVING: 'OBSERVING',
  RECOVERED: 'RECOVERED',
  ESCALATED: 'ESCALATED',
  STOPPED: 'STOPPED',
  EXPIRED: 'EXPIRED'
};

export const AUDIT_ACTORS = {
  SYSTEM: 'SYSTEM',
  AI_AGENT: 'AI_AGENT',
  POLICY_ENGINE: 'POLICY_ENGINE',
  SIMULATOR: 'SIMULATOR',
  HUMAN: 'HUMAN'
};

